name: Code Analysis

on:
  push:
  schedule:
    - cron: "0 4 * * *"

jobs:
  analyze:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          pip install openai tiktoken

      - name: Create analysis script
        run: |
          cat << 'EOF' > analysis.py
from openai import OpenAI
import os

client = OpenAI(api_key=os.environ["OPENAI_API_KEY"])

files = []
for root, _, filenames in os.walk(".", topdown=True):
    for filename in filenames:
        if filename.endswith(".py"):
            try:
                with open(os.path.join(root, filename), "r", errors="ignore") as f:
                    files.append(f.read())
            except:
                pass

response = client.chat.completions.create(
    model="gpt-4o-mini",
    messages=[
        {"role": "system", "content": "You are a code analysis engine."},
        {"role": "user", "content": "Analyze this code base:\n\n" + str(files[:50])}
    ]
)

report = response.choices[0].message["content"]

with open("CODE_ANALYSIS.md", "w") as f:
    f.write("# Automated Code Report\n\n")
    f.write(report)
EOF

      - name: Run analysis
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          python3 analysis.py

      - name: Commit report
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add CODE_ANALYSIS.md
          git commit -m "Update automated code analysis" || true
          git push